# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/laotang013/ModulizedDemo.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'A' do
 
end
